apiVersion: v1
kind: Secret
metadata:
  name: reference-data-aggregator-secret
  labels:
    app: reference-data-aggregator
type: Opaque
data:
  # Base64 encoded placeholder credentials for upstream services
  RDAS_SOAP_USERNAME: dXNlcm1hbWU= # base64 for 'username'
  RDAS_SOAP_PASSWORD: cGFzc3dvcmQ= # base64 for 'password'
