apiVersion: v1
kind: Service
metadata:
  name: reference-data-aggregator
  labels:
    app: reference-data-aggregator
spec:
  selector:
    app: reference-data-aggregator
  ports:
    - port: 80
      targetPort: 8080
      name: http
  type: ClusterIP
